name: C/C++ CI

on:
  push:
    branches: [ "Main" ]
  pull_request:
    branches: [ "Main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: sudo apt install cmake
    - name: cmake
      run: cmake --build build --target enigma -j 3
